"""Inference regression: window scores and AUC of the current code match the code before the move into the package.

The reference (tests/golden/golden.json) was generated by tests/golden/make_golden.py from the old code.
Two cases:
- FLASK.pt: a real old checkpoint loads and gives the same scores. Its vocab
  barely covers the fixtures (process is always UNK), so it barely checks encoding;
- FIXT.pt: a mini-training checkpoint whose vocab was built on the same data.
"""

import json
from pathlib import Path

import pytest
import torch
from sklearn.metrics import roc_auc_score

from syscall_hids.cli.eval_recordings import score_log_file
from syscall_hids.modules.models import SyscallLSTM

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
TOL = 1e-6
# case -> (checkpoint, directory with normal/ and abnormal/, reference key in golden.json; None: root)
CASES = {
    "FLASK": ("FLASK.pt", GOLDEN_DIR / "data", None),
    "FIXT": ("FIXT.pt", GOLDEN_DIR / "data" / "FIXT" / "test", "fixt_inference"),
}


@pytest.fixture(scope="module", params=list(CASES))
def case(request) -> tuple[dict, dict[str, list[float]]]:
    """(reference with auc/scores keys, current scores) for one checkpoint."""
    ckpt_name, data_dir, key = CASES[request.param]
    golden = json.loads((GOLDEN_DIR / "golden.json").read_text(encoding="utf-8"))
    golden = golden if key is None else golden[key]

    device = torch.device("cpu")
    checkpoint = torch.load(GOLDEN_DIR / ckpt_name, map_location=device)
    model = SyscallLSTM.from_checkpoint(checkpoint, device)
    model.eval()
    # batch_size=32 is the former config.BATCH_SIZE used for the reference
    current = {name: score_log_file(model, checkpoint, str(data_dir / name), device, 32) for name in golden["scores"]}
    return golden, current


def test_window_scores_match(case) -> None:
    golden, current_scores = case
    for name, expected in golden["scores"].items():
        actual = current_scores[name]
        assert len(actual) == len(expected), f"{name}: window count {len(actual)} != {len(expected)}"
        worst = max(abs(a - e) for a, e in zip(actual, expected))
        assert worst <= TOL, f"{name}: max score deviation {worst:.3e} > {TOL}"


def test_auc_matches(case) -> None:
    golden, current_scores = case
    truth: list[bool] = []
    flat: list[float] = []
    for name, scores in current_scores.items():
        truth += [name.startswith("abnormal/")] * len(scores)
        flat += scores
    assert abs(roc_auc_score(truth, flat) - golden["auc"]) <= TOL
